shop/mainapp/urls.py
from django.urls import path

from .views import test_view, ProductDetailView

urlpatterns = [
    path('', test_view, name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/mainapp/models.py
import sys
from PIL import Image

from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.files.uploadedfile import InMemoryUploadedFile
from io import BytesIO
from django.urls import reverse

User = get_user_model()


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class MinResolutionErrorException(Exception):
    pass


class MaxResolutionErrorException(Exception):
    pass


class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_models.exists():
                if with_respect_to in args:
                    return sorted(products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to),
                                  reverse=True)
        return products


class LatestProducts:
    objects = LatestProductsManager()


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    MIN_RESOLUTION = (400, 400)
    MAX_RESOLUTION = (800, 800)
    MAX_IMAGE_SIZE = 3145728

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.title

    # работа с размером изображения

    # def save(self, *args, **kwargs):
    #     image = self.image
    #     img = Image.open(image)
    #     min_height, min_width = self.MIN_RESOLUTION
    #     max_height, max_width = self.MAX_RESOLUTION
    #     if img.height < min_height or img.width < min_width:
    #         raise MinResolutionErrorException('Разрешение изображения меньше минимального!')
    #     if img.height > max_height or img.width > max_width:
    #         raise MaxResolutionErrorException('Разрешение изображения больше максимального!')
    # image = self.image
    # img = Image.open(image)
    # new_img = img.convert('RGB')
    # resized_new_img = new_img.resize((200, 200), Image.ANTIALIAS)
    # filestream = BytesIO()
    # resized_new_img.save(filestream, 'JPEG', quality =90)
    # filestream.seek(0)
    # name = "{}.{}".format(*self.image.name.split('.'))
    # self.image = InMemoryUploadedFile(
    #     filestream, 'ImageField', name, 'jpeg/image', sys.getsizeof(filestream), None
    # )
    # super().save(*args, **kwargs)


class Notebook(Product):
    diagonal = models.CharField(max_length=225, verbose_name='Диагональ')
    display_type = models.CharField(max_length=225, verbose_name='Тип дисплея')
    processor_freq = models.CharField(max_length=225, verbose_name='Частота процессора')
    ram = models.CharField(max_length=225, verbose_name='Оперативная память')
    video = models.CharField(max_length=225, verbose_name='Видео карта')
    time_without_charge = models.CharField(max_length=225, verbose_name='Время работы аакумулятора')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Smartphone(Product):
    diagonal = models.CharField(max_length=225, verbose_name='Диагональ')
    display_type = models.CharField(max_length=225, verbose_name='Тип дисплея')
    resolution = models.CharField(max_length=225, verbose_name='Разрешение экрана')
    accum_volume = models.CharField(max_length=225, verbose_name='Ёмкость аккумулятора')
    ram = models.CharField(max_length=225, verbose_name='Оперативная память')
    sd = models.BooleanField(default=True, verbose_name='Наличие SD карты')
    sd_volume_max = models.CharField(
        max_length=225, null=True, blank=True, verbose_name='Максимальный объем встраиваемой памяти')
    main_cam_mp = models.CharField(max_length=225, verbose_name='Главная камера')
    frontal_cam_mp = models.CharField(max_length=225, verbose_name='Фронтальная камера')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')

    # @property
    # def sd(self):
    #     if self.sd:
    #         return 'Да'
    #     return 'Нет'


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Card', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return 'Продукт: {}(для корзины)'.format(self.content_object.title)


class Card(models.Model):
    owner = models.ForeignKey('Customer', verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона')
    address = models.CharField(max_length=20, verbose_name='Адрес')

    def __str__(self):
        return 'Покупатель:{} {}'.format(self.user.first_name, self.user.last_name)

shop/mainapp/views.py
from django.shortcuts import render
from django.views.generic import DetailView

from .models import Notebook, Smartphone


def test_view(request):
    return render(request, 'base.html', {})


class ProductDetailView(DetailView):

    CT_MODEL_MODEL_CLASS = {
        'notebook': Notebook,
        'smartphone': Smartphone
    }

    def dispatch(self, request, *args, **kwargs):
        self.model = self.CT_MODEL_MODEL_CLASS[kwargs['ct_model']]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, **kwargs)

    context_object_name = 'product'
    template_name = 'product_detail.html'
    slug_url_kwarg = 'slug'

shop/mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
    $('#id_sd').on('click',function(){
        if($('#id_sd').prop('checked') == true){
            $('#id_sd_volume_max').prop('readonly', false)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'white')
        }else{
            $('#id_sd_volume_max').prop('readonly', true)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'Lightgray')
        }
    })
})(django.jQuery);
</script>
{% endblock %}

shop/mainapp/templates/notebook_specification.html
<table class="table">
  <tbody>
    <tr>
      <td>Диагональ</td>
      <td>{{ product.diagonal }}</td>
    </tr>
      <tr>
      <td>Тип дисплея</td>
      <td>{{ product.display_type }}</td>
    </tr>
      <tr>
      <td>Частота процессора</td>
      <td>{{ product.processor_freq }}</td>
    </tr>
      <tr>
      <td>Оперативная память</td>
      <td>{{ product.ram }}</td>
    </tr>
      <tr>
      <td>Видеокарта</td>
      <td>{{ product.video }}</td>
    </tr>
      <tr>
      <td>Время работы аккумулятора</td>
      <td>{{ product.time_without_charge }}</td>
    </tr>
  </tbody>
</table>

shop/mainapp/templates/product_detail.html
{% extends 'base.html' %}
{% load specifications %}
{% block content %}
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
    <li class="breadcrumb-item"><a href="#">{{ product.category.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
  </ol>
</nav>

<div class ='row'>
    <div class='col_md_4'>
        <img src="{{ product.image.url }}" class="img-fluid" width="150" height="200">
    </div>
    <div class="col_md_8">
        <h3>{{ product.title }}</h3>
        <p>Цена: {{ product.price }} руб.</p>
        <p>Описание: {{product_description }}</p>
    </div>
    <p class="mt=4">Характеристики: </p>

    {{ product|product_spec }}

</div>

{% endblock content %}

shop/mainapp/templates/smartphone_specification.html
<table class="table">
  <tbody>
    <tr>
      <td>Диагональ</td>
      <td>{{ product.diagonal }}</td>
    </tr>
      <tr>
      <td>Тип дисплея</td>
      <td>{{ product.display_type }}</td>
    </tr>
      <tr>
      <td>Разрешение экрана</td>
      <td>{{ product.resolution }}</td>
    </tr>
      <tr>
      <td>Ёмкость аккумулятора</td>
      <td>{{ product.accum_volume }}</td>
    </tr>
      <tr>
      <td>Оперативная память</td>
      <td>{{ product.ram }}</td>
    </tr>
      <tr>
      <td>Наличие слота для SD карты</td>
      <td>{{ product.sd }}</td>
      </tr>
    <tr>
      <td>Максимальный объем встраиваемой памяти</td>
      <td>{{ product.sd_volume_max }}</td>
    </tr>
      <tr>
      <td>Камера</td>
      <td>{{ product.main_cam_mp }}</td>
    </tr>
      <tr>
      <td>Фронтальная камера</td>
      <td>{{ product.frontal_cam_mp }}</td>
    </tr>
  </tbody>
</table>